import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/styles/globals.css'
import Nav from '@/components/nav'

export const dynamic = 'force-dynamic'

const sfRoundMedium = localFont({
  src: '../public/fonts/sf-round-medium.otf',
  weight: '500',
  variable: '--font-sfRoundMedium',
});

const sfRoundBold = localFont({
  src: '../public/fonts/sf-round-bold.otf',
  weight: '700',
  variable: '--font-sfRoundBold',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sfRoundMedium.className} scroll-smooth text-newblack bg-newwhite`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}